/**
 * Copyright (c) 2017-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

module.exports = {
  docs: {
    'Başlangıç': [
      'tr-introduction',
    ],
    'Bilgi': [
      'info/tr-scss',
      'info/tr-smarty',
    ],
    'Yerleşim': [
      'css/tr-layout-containers',
      'css/tr-layout-grid',
      'css/tr-layout-alignments',
      'css/tr-layout-orders',
      'css/tr-layout-gutters',
      'css/tr-layout-utilities',
    ],
    'Özelleştirme': [
      'css/tr-customize-colors',
    ],
    'İçerik': [
      'css/tr-content-reboot',
      'css/tr-content-typography',
      'css/tr-content-images',
      'css/tr-content-animations',
    ],
    'Araçlar': [
      'css/tr-utilities-flex',
      'css/tr-utilities-background',
      'css/tr-utilities-borders',
      'css/tr-utilities-overflow',
      'css/tr-utilities-position',
      'css/tr-utilities-sizing',
      'css/tr-utilities-spacing',
      'css/tr-utilities-text',
    ],
    'Bileşenler': [
      'css/tr-components-icons',
      'css/tr-components-buttons',
      'css/tr-components-badge',
    ],
    '* JavaScript': [
      'js/tr-javascript',
      'js/tr-javascript-selector',
      'js/tr-javascript-component',
      'js/tr-javascript-component-dropdown',
      'js/tr-javascript-component-accordion',
      'js/tr-javascript-component-tab',
      'js/tr-javascript-component-notify',
      'js/tr-javascript-component-placeholder',
      'js/tr-javascript-component-modal',
      'js/tr-javascript-component-popupwin',
      'js/tr-javascript-component-tooltip',
      'js/tr-javascript-component-drawer',
      'js/tr-javascript-component-check-validity',
      'js/tr-javascript-component-qty',
      'js/tr-javascript-component-login-form',
      'js/tr-javascript-component-setlanguage',
      'js/tr-javascript-component-setcurrency',
      'js/tr-javascript-component-vat',
      'js/tr-javascript-component-format',
      'js/tr-javascript-component-time-converter',
      'js/tr-javascript-component-affix',
      'js/tr-javascript-component-button-lock',
      'js/tr-javascript-component-input-file',
      'js/tr-javascript-component-equal-height',
      'js/tr-javascript-component-mask',
    ],
    '* Servisler (legacy)': [
      'api/tr-all-info-about-services',
      'api/tr-product',
      'api/tr-address',
      'api/tr-brand',
      'api/tr-cart',
      'api/tr-category',
      'api/tr-combine',
      'api/tr-compare',
      'api/tr-conf',
      'api/tr-content',
      'api/tr-content-v5',
      'api/tr-customer',
      'api/tr-customer-service',
      'api/tr-customer-v5',
      'api/tr-e-invoice',
      'api/tr-filter',
      'api/tr-gallery',
      'api/tr-guest',
      'api/tr-guest-v5',
      'api/tr-hopi',
      'api/tr-iyzico',
      'api/tr-language',
      'api/tr-model',
      'api/tr-offer',
      'api/tr-order',
      'api/tr-order-v4',
      'api/tr-order-v5',
      'api/tr-personalization',
      'api/tr-pritracker',
      'api/tr-product-detail',
      'api/tr-product-showcase',
      'api/tr-profile',
      'api/tr-region',
      'api/tr-service',
      'api/tr-showcase',
      'api/tr-site',
      'api/tr-store',
      'api/tr-supplier',
      'api/tr-variant',
      'api/tr-zubizu',
      'api/tr-product-get-related-products-1',
      'api/tr-product-get-related-products-2',
      'api/tr-product-get-related-products-3',
      'api/tr-product-get-related-products-4',
    ],
    '* Servisler V5': [
      'apiv5/tr-general',
      'apiv5/tr-filemanager',
      'apiv5/tr-address',
      'apiv5/tr-messages',
    ],
  },
};
