/**
 * Copyright (c) 2017-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

module.exports = {
  docs: {
    'Başlangıç': [
      'tr-introduction',
      'tr-vscode-extension',
    ],
    'Bilgi': [
      'info/tr-tree-folder',
      'info/tr-scss',
      'info/tr-smarty',
      'info/tr-setting-json',
    ],
    'Yerleşim': [
      'css/tr-layout-containers',
      'css/tr-layout-grid',
      'css/tr-layout-alignments',
      'css/tr-layout-orders',
      'css/tr-layout-gutters',
      'css/tr-layout-utilities',
    ],
    'Özelleştirme': [
      'css/tr-customize-colors',
    ],
    'İçerik': [
      'css/tr-content-reboot',
      'css/tr-content-typography',
      'css/tr-content-images',
      'css/tr-content-animations',
      'css/tr-content-effects',
      'css/tr-content-overlay',
    ],
    'Araçlar': [
      'css/tr-utilities-flex',
      'css/tr-utilities-background',
      'css/tr-utilities-borders',
      'css/tr-utilities-overflow',
      'css/tr-utilities-position',
      'css/tr-utilities-sizing',
      'css/tr-utilities-spacing',
      'css/tr-utilities-shadows',
    ],
    'Bileşenler': [
      'css/tr-components-icons',
      'css/tr-components-buttons',
      'css/tr-components-badge',
    ],
    '* JavaScript': [
      'js/tr-javascript',
      'js/tr-javascript-selector',
      'components/tr-javascript-component-accordion',
      'components/tr-javascript-component-affix',
      'components/tr-javascript-component-button-lock',
      'components/tr-javascript-component-cartcallback',
      'components/tr-javascript-component-check-validity',
      'components/tr-javascript-component-cookie',
      'components/tr-javascript-component-evalscript',
      'components/tr-javascript-component-format',
      'components/tr-javascript-component-getlink',
      'components/tr-javascript-component-loadsubfolder',
      'components/tr-javascript-component-localapi',
      'components/tr-javascript-component-modal',
      'components/tr-javascript-component-notify',
      'components/tr-javascript-component-time-converter',
      'components/tr-javascript-component-vat',
    ],
    '* Smarty': [
      'smarty/tr-smarty',
      'components/tr-smarty-component-addfavbtn',
      'components/tr-smarty-component-countdown',
      'components/tr-smarty-component-drawer',
      'components/tr-smarty-component-dropdown',
      'components/tr-smarty-component-equal-height',
      'components/tr-smarty-component-input-file',
      'components/tr-smarty-component-login-form',
      'components/tr-smarty-component-mask',
      'components/tr-smarty-component-placeholder',
      'components/tr-smarty-component-popconfirm',
      'components/tr-smarty-component-popoveralert',
      'components/tr-smarty-component-popupwin',
      'components/tr-smarty-component-qty',
      'components/tr-smarty-component-setcurrency',
      'components/tr-smarty-component-setlanguage',
      'components/tr-smarty-component-snapscroll',
      'components/tr-smarty-component-socialgoogle',
      'components/tr-smarty-component-sticky',
      'components/tr-smarty-component-subscribe',
      'components/tr-smarty-component-tab',
      'components/tr-smarty-component-tooltip',
      'components/tr-smarty-component-variant',
      'components/tr-smarty-component-zoom',
    ],
    '* Servisler V5': [
      'api-v5/tr-general',
      'api-v5/tr-filemanager',
      'api-v5/tr-address',
      'api-v5/tr-messages',
      'api-v5/tr-member-login-methods',
    ],
    '* Extra': [
      'extra/tr-detail-asorti-ERP',
      'extra/tr-detail-vertical-accordion',
      'extra/tr-detail-change-main-image',
      'extra/tr-detail-which-store-ERP',
      'extra/tr-list-horizontal-sort',
      'extra/tr-list-instock',
      'extra/tr-list-variant-image',
      'extra/tr-filter-close',
      'extra/tr-lightgallery',
      'extra/tr-list-detail-extra-discount',
      'extra/tr-readmore',
      'extra/tr-image-map',
      'extra/tr-showcase-dowry-percent',
      'extra/tr-delivery-country',
      'extra/tr-customer-current-payment-cari-ERP',
    ],
  },
};